"""add medication_events table

Revision ID: 6c1096ccdc22
Revises: 5f25be62ebd8
Create Date: 2026-09-18 15:02:16.796070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1096ccdc22'
down_revision: Union[str, Sequence[str], None] = '5f25be62ebd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('upcoming', 'taken', 'missed', 'skipped', 'delayed', name='medicationeventstatus'), nullable=False),
    sa.Column('actual_taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['medication_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'scheduled_at', name='uq_schedule_scheduled_at')
    )
    op.create_index(op.f('ix_medication_events_schedule_id'), 'medication_events', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_events_schedule_id'), table_name='medication_events')
    op.drop_table('medication_events')
    # ### end Alembic commands ###
